export { default as User } from "./User";
export { default as Lead } from "./Lead";
export { default as Customer } from "./Customer";
export { default as Property } from "./Property";
export { default as Project } from "./Project";
export { default as FollowUp } from "./FollowUp";
export { default as SiteVisit } from "./SiteVisit";
export { default as Deal } from "./Deal";
export { default as Payment } from "./Payment";
export { default as Commission } from "./Commission";
export { default as Document } from "./Document";
export { default as Activity } from "./Activity";

export type { IUser } from "./User";
export type { ILead } from "./Lead";
export type { ICustomer } from "./Customer";
export type { IProperty } from "./Property";
export type { IProject } from "./Project";
export type { IFollowUp } from "./FollowUp";
export type { ISiteVisit } from "./SiteVisit";
export type { IDeal } from "./Deal";
export type { IPayment } from "./Payment";
export type { ICommission } from "./Commission";
export type { IDocument } from "./Document";
export type { IActivity } from "./Activity";
